include:
  - '.gitlab-vars.yml' #Import env vars

services:
- ${DOCKER_SERVICE}

stages:
  - lint
  - docker_build
  - docker_push
  #- test
  - release

lint:
  stage: lint
  except:
    - tags
  image: {$LINT_IMAGE}
  before_script:
    # Show the PowerShell version
    - pwsh -Version
  script:
    # Execute recursively the analyzer
    - ${LINT_CMD}

docker_build:
  stage: docker_build
  except:
    - merge_requests
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
      docker build
      --pull
      --cache-from ${LATEST_TAG}
      --tag ${COMMIT_TAG}
      .
  dependencies:
    - lint

docker_push:
  stage: docker_push
  except:
    - merge_requests
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - docker push ${COMMIT_TAG}
    - docker tag ${COMMIT_TAG} ${LATEST_TAG}
    - docker push ${LATEST_TAG}
  dependencies:
    - docker_build

release:
  stage: release
  only:
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - docker pull ${LATEST_TAG}
    - docker tag ${LATEST_TAG} ${RELEASE_TAG}
    - docker push ${RELEASE_TAG}