variables:
  #Linter
  LINT_CMD: 'pwsh -Command "Invoke-ScriptAnalyzer -EnableExit -Recurse -Severity Error -Path ."'
  #Docker
  LATEST_TAG: "${CI_REGISTRY_IMAGE}:latest"
  COMMIT_TAG: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  RELEASE_TAG: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"