variables:
  #Linter
  LINT_IMAGE: ${CI_REGISTRY_IMAGE}/lint:latest
  LINT_CMD: 'pwsh -Command "Invoke-ScriptAnalyzer -EnableExit -Recurse -Severity Error -Path ."'
  #Docker
  DOCKER_SERVICE: docker:20.10.8-dind
  DOCKER_IMAGE: docker:20.10.8-dind-alpine3.13
  DOCKER_LINT_IMAGE: hadolint/hadolint:latest-alpine
  DOCKERFILE_PATH: ${CI_PROJECT_DIR}/.docker/app
  DOCKERFILE_LINT_PATH: ${CI_PROJECT_DIR}/.docker/lint
  DOCKER_LINT_CMD: hadolint
  LATEST_TAG: ${CI_REGISTRY_IMAGE}:latest
  COMMIT_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  RELEASE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  LINT_LATEST_TAG: ${CI_REGISTRY_IMAGE}/lint:latest
  LINT_COMMIT_TAG: ${CI_REGISTRY_IMAGE}/lint:${CI_COMMIT_SHORT_SHA}
  LINT_RELEASE_TAG: ${CI_REGISTRY_IMAGE}/lint:${CI_COMMIT_TAG}