Smoke Test Dockerfile Lint:
  stage: Lint
  only:
    changes:
      - .docker/smoketest/*
  image: ${DOCKER_LINT_IMAGE}
  script: ${DOCKER_LINT_CMD} ${DOCKERFILE_SMOKE_TEST_PATH}/Dockerfile

Smoke Test Build:
  stage: Smoke Test Build
  only:
    changes:
      - conv2mp4.ps1
      - files/**/*
      - .docker/smoketest/*
  except:
    - merge_requests
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - echo 'Fetching latest smoke test suite artifact...'
    - 'wget --header="JOB-TOKEN: ${CI_JOB_TOKEN}" ${SMOKE_TEST_SUITE_URI} -P ${DOCKERFILE_SMOKE_TEST_PATH}'
    - >
      docker build
      --pull
      --cache-from ${SMOKE_TEST_LATEST_TAG}
      --build-arg COMMIT=${CI_COMMIT_SHORT_SHA}
      --tag ${SMOKE_TEST_COMMIT_TAG}
      --file ${DOCKERFILE_SMOKE_TEST_PATH}/Dockerfile ${CI_PROJECT_DIR}
    - docker push ${SMOKE_TEST_COMMIT_TAG}

Smoke Test Push:
  stage: Publish
  only:
    changes:
      - .docker/smoketest/*
  except:
    - merge_requests
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - docker pull ${SMOKE_TEST_COMMIT_TAG}
    - docker tag ${SMOKE_TEST_COMMIT_TAG} ${SMOKE_TEST_LATEST_TAG}
    - docker push ${SMOKE_TEST_LATEST_TAG}