Dockerfile Lint:
  stage: Lint
  only:
    changes:
      - .docker/app/*
  image: ${DOCKER_LINT_IMAGE}
  script: ${DOCKER_LINT_CMD} ${DOCKERFILE_PATH}/Dockerfile

Docker Build:
  stage: Build
  only:
    changes:
      - conv2mp4\.ps1
      - files/**/*
      - .docker/app/*
  except:
    - merge_requests
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - >
      docker build
      --pull
      --cache-from ${LATEST_TAG}
      --build-arg REVISION=${CI_COMMIT_SHA}
      --tag ${COMMIT_TAG}
      --file ${DOCKERFILE_PATH}/Dockerfile ${CI_PROJECT_DIR}
    - docker push ${COMMIT_TAG}

Docker Push:
  stage: Publish
  only:
    changes:
      - conv2mp4\.ps1
      - files/**/*
      - .docker/app/*
  except:
    - merge_requests
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
  script:
    - docker pull ${COMMIT_TAG}
    - docker tag ${COMMIT_TAG} ${LATEST_TAG}
    - docker push ${LATEST_TAG}

Release:
  stage: Release
  only:
    - tags
  image: ${DOCKER_IMAGE}
  before_script:
    - echo -n ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
    - docker login -u ${DOCKERHUB_REGISTRY_USER} -p ${DOCKERHUB_REGISTRY_PASSWORD} ${DOCKERHUB_REGISTRY}
  script:
    - docker pull ${LATEST_TAG}
    - docker tag ${LATEST_TAG} ${RELEASE_TAG}
    - docker push ${RELEASE_TAG}
    - docker push ${DOCKERHUB_RELEASE_TAG}